# Generated by Django 4.1.7 on 2023-03-31 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ingresa el nombre', max_length=40)),
                ('apellido', models.CharField(help_text='Ingresa el apellido', max_length=40)),
                ('genero', models.CharField(help_text='Ingresa el genero', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='nombredecarpeta')),
                ('titulo', models.CharField(help_text='Ingresa el título', max_length=100)),
                ('descripcion', models.CharField(help_text='Ingresa una breve descripción', max_length=300)),
                ('autor', models.CharField(max_length=40)),
                ('profesion', models.CharField(max_length=40)),
                ('fechaPublicacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
