# Generated by Django 4.1.7 on 2023-04-01 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalGavino', '0004_posteo_delete_publicacion_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='contacto',
            name='descripcion',
            field=models.TextField(help_text='Ingresa una breve descripción', max_length=300),
        ),
    ]
