# Generated by Django 4.1.7 on 2023-04-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalGavino', '0006_alter_contacto_celular'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contact',
        ),
    ]
