# Generated by Django 4.1.7 on 2023-04-05 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalGavino', '0009_remove_posteo_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posteo',
            name='user',
        ),
    ]
