# Generated by Django 4.1.7 on 2023-04-06 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyectoFinalGavino', '0010_remove_posteo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='descripcion',
            new_name='mensaje',
        ),
    ]
